name: Node CI
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
jobs:
  lint-and-test:
    name: 'Lint & Tests'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Set up Node.js
        uses: actions/setup-node@master
      - name: Installing Deps
        run: |
          yarn install
      - name: Lint & Tests
        run: |
          yarn run test:cov
      - name: Upload Code Coverage
        uses: codecov/codecov-action@v1.0.3
        with:
          token: ${{secrets.CODECOV_TOKEN}}
          file: ./coverage/lcov.info
